// Code generated by protoc-gen-go.
// source: router.proto
// DO NOT EDIT!

/*
Package intra is a generated protocol buffer package.

It is generated from these files:
	router.proto

It has these top-level messages:
	ReadMetricsInfo
	ReadMetricsResponse
*/
package intra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadMetricsInfo struct {
	File string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
}

func (m *ReadMetricsInfo) Reset()                    { *m = ReadMetricsInfo{} }
func (m *ReadMetricsInfo) String() string            { return proto.CompactTextString(m) }
func (*ReadMetricsInfo) ProtoMessage()               {}
func (*ReadMetricsInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadMetricsInfo) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type ReadMetricsResponse struct {
	WriteCount uint64 `protobuf:"varint,1,opt,name=writeCount" json:"writeCount,omitempty"`
	ErrCount   uint64 `protobuf:"varint,2,opt,name=errCount" json:"errCount,omitempty"`
}

func (m *ReadMetricsResponse) Reset()                    { *m = ReadMetricsResponse{} }
func (m *ReadMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadMetricsResponse) ProtoMessage()               {}
func (*ReadMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadMetricsResponse) GetWriteCount() uint64 {
	if m != nil {
		return m.WriteCount
	}
	return 0
}

func (m *ReadMetricsResponse) GetErrCount() uint64 {
	if m != nil {
		return m.ErrCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ReadMetricsInfo)(nil), "intra.ReadMetricsInfo")
	proto.RegisterType((*ReadMetricsResponse)(nil), "intra.ReadMetricsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Router service

type RouterClient interface {
	ReadMetrics(ctx context.Context, in *ReadMetricsInfo, opts ...grpc.CallOption) (*ReadMetricsResponse, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) ReadMetrics(ctx context.Context, in *ReadMetricsInfo, opts ...grpc.CallOption) (*ReadMetricsResponse, error) {
	out := new(ReadMetricsResponse)
	err := grpc.Invoke(ctx, "/intra.Router/ReadMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Router service

type RouterServer interface {
	ReadMetrics(context.Context, *ReadMetricsInfo) (*ReadMetricsResponse, error)
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_ReadMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMetricsInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).ReadMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intra.Router/ReadMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).ReadMetrics(ctx, req.(*ReadMetricsInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intra.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadMetrics",
			Handler:    _Router_ReadMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}

func init() { proto.RegisterFile("router.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcc, 0x2b, 0x29, 0x4a, 0x54,
	0x52, 0xe5, 0xe2, 0x0f, 0x4a, 0x4d, 0x4c, 0xf1, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x2e, 0xf6, 0xcc,
	0x4b, 0xcb, 0x17, 0x12, 0xe2, 0x62, 0x49, 0xcb, 0xcc, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0x02, 0xb9, 0x84, 0x91, 0x94, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x0a, 0xc9, 0x71, 0x71, 0x95, 0x17, 0x65, 0x96, 0xa4, 0x3a, 0xe7, 0x97, 0xe6, 0x95, 0x80,
	0x35, 0xb0, 0x04, 0x21, 0x89, 0x08, 0x49, 0x71, 0x71, 0xa4, 0x16, 0x15, 0x41, 0x64, 0x99, 0xc0,
	0xb2, 0x70, 0xbe, 0x91, 0x2f, 0x17, 0x5b, 0x10, 0xd8, 0x41, 0x42, 0xce, 0x5c, 0xdc, 0x48, 0x86,
	0x0b, 0x89, 0xe9, 0x81, 0x9d, 0xa6, 0x87, 0xe6, 0x2e, 0x29, 0x29, 0x4c, 0x71, 0x98, 0x43, 0x94,
	0x18, 0x92, 0xd8, 0xc0, 0xde, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x86, 0xd8, 0x90, 0x0e,
	0xe6, 0x00, 0x00, 0x00,
}
