// Code generated by protoc-gen-go.
// source: analyst.proto
// DO NOT EDIT!

/*
Package loggrebutterfly is a generated protocol buffer package.

It is generated from these files:
	analyst.proto
	data_node.proto
	master.proto

It has these top-level messages:
	QueryInfo
	AggregateInfo
	QueryResponse
	AggregateResponse
	AnalystFilter
	TimeRange
	CounterFilter
	WriteInfo
	WriteResponse
	ReadInfo
	ReadData
	RoutesInfo
	RoutesResponse
	RouteInfo
	AnalystsInfo
	AnalystsResponse
	AnalystInfo
*/
package loggrebutterfly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import loggregator_v2 "github.com/apoydence/loggrebutterfly/api/loggregator/v2"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryInfo struct {
	Filter *AnalystFilter `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
}

func (m *QueryInfo) Reset()                    { *m = QueryInfo{} }
func (m *QueryInfo) String() string            { return proto.CompactTextString(m) }
func (*QueryInfo) ProtoMessage()               {}
func (*QueryInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryInfo) GetFilter() *AnalystFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type AggregateInfo struct {
	Query         *QueryInfo `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	BucketWidthNs int64      `protobuf:"varint,2,opt,name=bucket_width_ns,json=bucketWidthNs" json:"bucket_width_ns,omitempty"`
}

func (m *AggregateInfo) Reset()                    { *m = AggregateInfo{} }
func (m *AggregateInfo) String() string            { return proto.CompactTextString(m) }
func (*AggregateInfo) ProtoMessage()               {}
func (*AggregateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AggregateInfo) GetQuery() *QueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *AggregateInfo) GetBucketWidthNs() int64 {
	if m != nil {
		return m.BucketWidthNs
	}
	return 0
}

type QueryResponse struct {
	Envelopes []*loggregator_v2.Envelope `protobuf:"bytes,1,rep,name=envelopes" json:"envelopes,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryResponse) GetEnvelopes() []*loggregator_v2.Envelope {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

type AggregateResponse struct {
	Results map[int64]float64 `protobuf:"bytes,1,rep,name=results" json:"results,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *AggregateResponse) Reset()                    { *m = AggregateResponse{} }
func (m *AggregateResponse) String() string            { return proto.CompactTextString(m) }
func (*AggregateResponse) ProtoMessage()               {}
func (*AggregateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AggregateResponse) GetResults() map[int64]float64 {
	if m != nil {
		return m.Results
	}
	return nil
}

type AnalystFilter struct {
	SourceId  string     `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	TimeRange *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	// Types that are valid to be assigned to Envelopes:
	//	*AnalystFilter_Counter
	Envelopes isAnalystFilter_Envelopes `protobuf_oneof:"Envelopes"`
}

func (m *AnalystFilter) Reset()                    { *m = AnalystFilter{} }
func (m *AnalystFilter) String() string            { return proto.CompactTextString(m) }
func (*AnalystFilter) ProtoMessage()               {}
func (*AnalystFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isAnalystFilter_Envelopes interface {
	isAnalystFilter_Envelopes()
}

type AnalystFilter_Counter struct {
	Counter *CounterFilter `protobuf:"bytes,3,opt,name=counter,oneof"`
}

func (*AnalystFilter_Counter) isAnalystFilter_Envelopes() {}

func (m *AnalystFilter) GetEnvelopes() isAnalystFilter_Envelopes {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

func (m *AnalystFilter) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *AnalystFilter) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *AnalystFilter) GetCounter() *CounterFilter {
	if x, ok := m.GetEnvelopes().(*AnalystFilter_Counter); ok {
		return x.Counter
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AnalystFilter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AnalystFilter_OneofMarshaler, _AnalystFilter_OneofUnmarshaler, _AnalystFilter_OneofSizer, []interface{}{
		(*AnalystFilter_Counter)(nil),
	}
}

func _AnalystFilter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AnalystFilter)
	// Envelopes
	switch x := m.Envelopes.(type) {
	case *AnalystFilter_Counter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Counter); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AnalystFilter.Envelopes has unexpected type %T", x)
	}
	return nil
}

func _AnalystFilter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AnalystFilter)
	switch tag {
	case 3: // Envelopes.counter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CounterFilter)
		err := b.DecodeMessage(msg)
		m.Envelopes = &AnalystFilter_Counter{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AnalystFilter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AnalystFilter)
	// Envelopes
	switch x := m.Envelopes.(type) {
	case *AnalystFilter_Counter:
		s := proto.Size(x.Counter)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// [start, end)
type TimeRange struct {
	Start int64 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TimeRange) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TimeRange) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type CounterFilter struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CounterFilter) Reset()                    { *m = CounterFilter{} }
func (m *CounterFilter) String() string            { return proto.CompactTextString(m) }
func (*CounterFilter) ProtoMessage()               {}
func (*CounterFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CounterFilter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryInfo)(nil), "loggrebutterfly.QueryInfo")
	proto.RegisterType((*AggregateInfo)(nil), "loggrebutterfly.AggregateInfo")
	proto.RegisterType((*QueryResponse)(nil), "loggrebutterfly.QueryResponse")
	proto.RegisterType((*AggregateResponse)(nil), "loggrebutterfly.AggregateResponse")
	proto.RegisterType((*AnalystFilter)(nil), "loggrebutterfly.AnalystFilter")
	proto.RegisterType((*TimeRange)(nil), "loggrebutterfly.TimeRange")
	proto.RegisterType((*CounterFilter)(nil), "loggrebutterfly.CounterFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Analyst service

type AnalystClient interface {
	Query(ctx context.Context, in *QueryInfo, opts ...grpc.CallOption) (*QueryResponse, error)
	Aggregate(ctx context.Context, in *AggregateInfo, opts ...grpc.CallOption) (*AggregateResponse, error)
}

type analystClient struct {
	cc *grpc.ClientConn
}

func NewAnalystClient(cc *grpc.ClientConn) AnalystClient {
	return &analystClient{cc}
}

func (c *analystClient) Query(ctx context.Context, in *QueryInfo, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/loggrebutterfly.Analyst/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analystClient) Aggregate(ctx context.Context, in *AggregateInfo, opts ...grpc.CallOption) (*AggregateResponse, error) {
	out := new(AggregateResponse)
	err := grpc.Invoke(ctx, "/loggrebutterfly.Analyst/Aggregate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analyst service

type AnalystServer interface {
	Query(context.Context, *QueryInfo) (*QueryResponse, error)
	Aggregate(context.Context, *AggregateInfo) (*AggregateResponse, error)
}

func RegisterAnalystServer(s *grpc.Server, srv AnalystServer) {
	s.RegisterService(&_Analyst_serviceDesc, srv)
}

func _Analyst_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalystServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggrebutterfly.Analyst/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalystServer).Query(ctx, req.(*QueryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyst_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalystServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggrebutterfly.Analyst/Aggregate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalystServer).Aggregate(ctx, req.(*AggregateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyst_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loggrebutterfly.Analyst",
	HandlerType: (*AnalystServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Analyst_Query_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _Analyst_Aggregate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyst.proto",
}

func init() { proto.RegisterFile("analyst.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0x56, 0xba, 0x92, 0x5b, 0xa2, 0x81, 0xc5, 0x43, 0x55, 0xa4, 0xaa, 0x0a, 0x12, 0xea,
	0x53, 0x82, 0x32, 0x69, 0x82, 0xbe, 0x8d, 0xa9, 0x83, 0xbe, 0x20, 0xcd, 0x42, 0xe2, 0xb1, 0x4a,
	0x93, 0xdb, 0x2c, 0x5a, 0x6a, 0x07, 0xdb, 0x29, 0xca, 0xaf, 0xf0, 0xca, 0x0f, 0xf0, 0x89, 0x28,
	0xb6, 0x13, 0xb6, 0x6e, 0x63, 0x6f, 0x37, 0xd7, 0xe7, 0x1e, 0xdf, 0x73, 0x8e, 0x03, 0x5e, 0xcc,
	0xe2, 0xa2, 0x96, 0x2a, 0x28, 0x05, 0x57, 0x9c, 0x9c, 0x14, 0x3c, 0xcb, 0x04, 0x6e, 0x2a, 0xa5,
	0x50, 0x6c, 0x8b, 0x7a, 0x72, 0x99, 0xe5, 0xea, 0xba, 0xda, 0x04, 0x09, 0xdf, 0x85, 0x71, 0xc9,
	0xeb, 0x14, 0x59, 0x82, 0xe1, 0x01, 0x2a, 0x8c, 0xcb, 0xdc, 0xf6, 0xb2, 0x58, 0x71, 0x11, 0xee,
	0xa3, 0x10, 0xd9, 0x1e, 0x0b, 0x5e, 0xa2, 0x21, 0xf6, 0x2f, 0xc0, 0xbd, 0xaa, 0x50, 0xd4, 0x2b,
	0xb6, 0xe5, 0xe4, 0x0c, 0x8e, 0xb7, 0x79, 0xa1, 0x50, 0x8c, 0x9d, 0x99, 0x33, 0x1f, 0x45, 0xd3,
	0xe0, 0x80, 0x30, 0x38, 0x37, 0x5b, 0x5d, 0x6a, 0x14, 0xb5, 0x68, 0x3f, 0x07, 0xef, 0xdc, 0x5e,
	0x82, 0x9a, 0xe8, 0x3d, 0x0c, 0x7e, 0x34, 0xac, 0x96, 0x67, 0x72, 0x8f, 0xa7, 0xbb, 0x93, 0x1a,
	0x20, 0x79, 0x07, 0x27, 0x9b, 0x2a, 0xb9, 0x41, 0xb5, 0xfe, 0x99, 0xa7, 0xea, 0x7a, 0xcd, 0xe4,
	0xf8, 0x68, 0xe6, 0xcc, 0xfb, 0xd4, 0x33, 0xed, 0xef, 0x4d, 0xf7, 0xab, 0xf4, 0x3f, 0x83, 0xa7,
	0x67, 0x29, 0xca, 0x92, 0x33, 0x89, 0xe4, 0x0c, 0xdc, 0x56, 0x92, 0x1c, 0x3b, 0xb3, 0xfe, 0x7c,
	0x14, 0x8d, 0x83, 0x5b, 0x9a, 0x83, 0x7d, 0x14, 0x2c, 0x2d, 0x80, 0xfe, 0x83, 0xfa, 0xbf, 0x1c,
	0x78, 0xd5, 0x2d, 0xdd, 0xb1, 0xad, 0x60, 0x28, 0x50, 0x56, 0x85, 0x6a, 0xb9, 0xc2, 0xfb, 0x16,
	0x1c, 0x0e, 0x05, 0xd4, 0x4c, 0x2c, 0x99, 0x12, 0x35, 0x6d, 0xe7, 0x27, 0x0b, 0x78, 0x71, 0xfb,
	0x80, 0xbc, 0x84, 0xfe, 0x0d, 0x1a, 0x47, 0xfa, 0xb4, 0x29, 0xc9, 0x6b, 0x18, 0xec, 0xe3, 0xa2,
	0x42, 0xad, 0xd4, 0xa1, 0xe6, 0x63, 0x71, 0xf4, 0xc1, 0xf1, 0xff, 0x38, 0xe0, 0xdd, 0xb1, 0x9a,
	0xbc, 0x01, 0x57, 0xf2, 0x4a, 0x24, 0xb8, 0xce, 0x53, 0xcd, 0xe1, 0xd2, 0xe7, 0xa6, 0xb1, 0x4a,
	0xc9, 0x47, 0x00, 0x95, 0xef, 0x70, 0x2d, 0x62, 0x96, 0x19, 0xb6, 0x87, 0x3c, 0xff, 0x96, 0xef,
	0x90, 0x36, 0x08, 0xea, 0xaa, 0xb6, 0x24, 0x0b, 0x18, 0x26, 0xbc, 0x62, 0x4d, 0xe6, 0xfd, 0x47,
	0x32, 0xbf, 0x30, 0xe7, 0x66, 0x91, 0x2f, 0x3d, 0xda, 0x0e, 0x7c, 0x1a, 0x81, 0xbb, 0xec, 0xfc,
	0x3c, 0x05, 0xb7, 0xbb, 0xa0, 0x51, 0x26, 0x55, 0x2c, 0x94, 0x55, 0x6b, 0x3e, 0x1a, 0x07, 0x90,
	0xa5, 0x36, 0xd7, 0xa6, 0xf4, 0xdf, 0x82, 0x77, 0x87, 0x9d, 0x10, 0x78, 0xc6, 0xe2, 0x1d, 0x5a,
	0x85, 0xba, 0x8e, 0x7e, 0x3b, 0x30, 0xb4, 0x66, 0x90, 0x25, 0x0c, 0x74, 0xfc, 0xe4, 0x3f, 0x4f,
	0x6a, 0x32, 0x7d, 0xf8, 0xac, 0xcd, 0xcb, 0xef, 0x91, 0x2b, 0x70, 0xbb, 0x18, 0xc9, 0xf4, 0xf1,
	0x88, 0x35, 0x9d, 0xff, 0xf4, 0x13, 0xf0, 0x7b, 0x9b, 0x63, 0xfd, 0x3f, 0x9d, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x61, 0x73, 0xd0, 0x48, 0xb9, 0x03, 0x00, 0x00,
}
