// Code generated by protoc-gen-go.
// source: analyst.proto
// DO NOT EDIT!

/*
Package loggrebutterfly is a generated protocol buffer package.

It is generated from these files:
	analyst.proto
	data_node.proto
	master.proto

It has these top-level messages:
	QueryInfo
	AggregateInfo
	AnalystFilter
	TimeRange
	QueryResponse
	AggregateResponse
	CounterAggregation
	WriteInfo
	WriteResponse
	ReadInfo
	ReadData
	RoutesInfo
	RoutesResponse
	RouteInfo
	AnalystsInfo
	AnalystsResponse
	AnalystInfo
*/
package loggrebutterfly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import loggregator_v2 "github.com/apoydence/loggrebutterfly/api/loggregator/v2"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryInfo struct {
	Filter *AnalystFilter `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
}

func (m *QueryInfo) Reset()                    { *m = QueryInfo{} }
func (m *QueryInfo) String() string            { return proto.CompactTextString(m) }
func (*QueryInfo) ProtoMessage()               {}
func (*QueryInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryInfo) GetFilter() *AnalystFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type AggregateInfo struct {
	Query         *QueryInfo `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	BucketWidthNs int64      `protobuf:"varint,2,opt,name=bucket_width_ns,json=bucketWidthNs" json:"bucket_width_ns,omitempty"`
	// Types that are valid to be assigned to Aggregation:
	//	*AggregateInfo_Counter
	Aggregation isAggregateInfo_Aggregation `protobuf_oneof:"Aggregation"`
}

func (m *AggregateInfo) Reset()                    { *m = AggregateInfo{} }
func (m *AggregateInfo) String() string            { return proto.CompactTextString(m) }
func (*AggregateInfo) ProtoMessage()               {}
func (*AggregateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isAggregateInfo_Aggregation interface {
	isAggregateInfo_Aggregation()
}

type AggregateInfo_Counter struct {
	Counter *CounterAggregation `protobuf:"bytes,3,opt,name=counter,oneof"`
}

func (*AggregateInfo_Counter) isAggregateInfo_Aggregation() {}

func (m *AggregateInfo) GetAggregation() isAggregateInfo_Aggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

func (m *AggregateInfo) GetQuery() *QueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *AggregateInfo) GetBucketWidthNs() int64 {
	if m != nil {
		return m.BucketWidthNs
	}
	return 0
}

func (m *AggregateInfo) GetCounter() *CounterAggregation {
	if x, ok := m.GetAggregation().(*AggregateInfo_Counter); ok {
		return x.Counter
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AggregateInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AggregateInfo_OneofMarshaler, _AggregateInfo_OneofUnmarshaler, _AggregateInfo_OneofSizer, []interface{}{
		(*AggregateInfo_Counter)(nil),
	}
}

func _AggregateInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AggregateInfo)
	// Aggregation
	switch x := m.Aggregation.(type) {
	case *AggregateInfo_Counter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Counter); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AggregateInfo.Aggregation has unexpected type %T", x)
	}
	return nil
}

func _AggregateInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AggregateInfo)
	switch tag {
	case 3: // Aggregation.counter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CounterAggregation)
		err := b.DecodeMessage(msg)
		m.Aggregation = &AggregateInfo_Counter{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AggregateInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AggregateInfo)
	// Aggregation
	switch x := m.Aggregation.(type) {
	case *AggregateInfo_Counter:
		s := proto.Size(x.Counter)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AnalystFilter struct {
	SourceId  string     `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	TimeRange *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
}

func (m *AnalystFilter) Reset()                    { *m = AnalystFilter{} }
func (m *AnalystFilter) String() string            { return proto.CompactTextString(m) }
func (*AnalystFilter) ProtoMessage()               {}
func (*AnalystFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AnalystFilter) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *AnalystFilter) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// [start, end)
type TimeRange struct {
	Start int64 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TimeRange) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TimeRange) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type QueryResponse struct {
	Envelopes []*loggregator_v2.Envelope `protobuf:"bytes,1,rep,name=envelopes" json:"envelopes,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryResponse) GetEnvelopes() []*loggregator_v2.Envelope {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

type AggregateResponse struct {
	Results map[int64]float64 `protobuf:"bytes,1,rep,name=results" json:"results,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *AggregateResponse) Reset()                    { *m = AggregateResponse{} }
func (m *AggregateResponse) String() string            { return proto.CompactTextString(m) }
func (*AggregateResponse) ProtoMessage()               {}
func (*AggregateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AggregateResponse) GetResults() map[int64]float64 {
	if m != nil {
		return m.Results
	}
	return nil
}

type CounterAggregation struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CounterAggregation) Reset()                    { *m = CounterAggregation{} }
func (m *CounterAggregation) String() string            { return proto.CompactTextString(m) }
func (*CounterAggregation) ProtoMessage()               {}
func (*CounterAggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CounterAggregation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryInfo)(nil), "loggrebutterfly.QueryInfo")
	proto.RegisterType((*AggregateInfo)(nil), "loggrebutterfly.AggregateInfo")
	proto.RegisterType((*AnalystFilter)(nil), "loggrebutterfly.AnalystFilter")
	proto.RegisterType((*TimeRange)(nil), "loggrebutterfly.TimeRange")
	proto.RegisterType((*QueryResponse)(nil), "loggrebutterfly.QueryResponse")
	proto.RegisterType((*AggregateResponse)(nil), "loggrebutterfly.AggregateResponse")
	proto.RegisterType((*CounterAggregation)(nil), "loggrebutterfly.CounterAggregation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Analyst service

type AnalystClient interface {
	Query(ctx context.Context, in *QueryInfo, opts ...grpc.CallOption) (*QueryResponse, error)
	Aggregate(ctx context.Context, in *AggregateInfo, opts ...grpc.CallOption) (*AggregateResponse, error)
}

type analystClient struct {
	cc *grpc.ClientConn
}

func NewAnalystClient(cc *grpc.ClientConn) AnalystClient {
	return &analystClient{cc}
}

func (c *analystClient) Query(ctx context.Context, in *QueryInfo, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/loggrebutterfly.Analyst/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analystClient) Aggregate(ctx context.Context, in *AggregateInfo, opts ...grpc.CallOption) (*AggregateResponse, error) {
	out := new(AggregateResponse)
	err := grpc.Invoke(ctx, "/loggrebutterfly.Analyst/Aggregate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analyst service

type AnalystServer interface {
	Query(context.Context, *QueryInfo) (*QueryResponse, error)
	Aggregate(context.Context, *AggregateInfo) (*AggregateResponse, error)
}

func RegisterAnalystServer(s *grpc.Server, srv AnalystServer) {
	s.RegisterService(&_Analyst_serviceDesc, srv)
}

func _Analyst_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalystServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggrebutterfly.Analyst/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalystServer).Query(ctx, req.(*QueryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyst_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalystServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggrebutterfly.Analyst/Aggregate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalystServer).Aggregate(ctx, req.(*AggregateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyst_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loggrebutterfly.Analyst",
	HandlerType: (*AnalystServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Analyst_Query_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _Analyst_Aggregate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyst.proto",
}

func init() { proto.RegisterFile("analyst.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x1b, 0xd2, 0xe0, 0x09, 0x56, 0x61, 0xc5, 0x21, 0x0a, 0x52, 0x14, 0x2d, 0x12, 0xca,
	0xc9, 0x46, 0xae, 0x54, 0x41, 0x2f, 0xa8, 0x54, 0x29, 0xe4, 0x82, 0xd4, 0x15, 0x12, 0xc7, 0xc8,
	0xb1, 0x27, 0xae, 0x55, 0x67, 0xd7, 0xac, 0xd7, 0x41, 0xfe, 0x15, 0xae, 0x7c, 0x05, 0x7f, 0x87,
	0xbc, 0xbb, 0x36, 0x21, 0x29, 0x70, 0x9b, 0x9d, 0x79, 0xf3, 0x66, 0xde, 0x3c, 0x1b, 0xbc, 0x88,
	0x47, 0x79, 0x5d, 0x2a, 0xbf, 0x90, 0x42, 0x09, 0x72, 0x96, 0x8b, 0x34, 0x95, 0xb8, 0xae, 0x94,
	0x42, 0xb9, 0xc9, 0xeb, 0xc9, 0x4d, 0x9a, 0xa9, 0xbb, 0x6a, 0xed, 0xc7, 0x62, 0x1b, 0x44, 0x85,
	0xa8, 0x13, 0xe4, 0x31, 0x06, 0x07, 0xa8, 0x20, 0x2a, 0x32, 0x9b, 0x4b, 0x23, 0x25, 0x64, 0xb0,
	0x0b, 0x03, 0xe4, 0x3b, 0xcc, 0x45, 0x81, 0x86, 0x98, 0x5e, 0x83, 0x7b, 0x5b, 0xa1, 0xac, 0x97,
	0x7c, 0x23, 0xc8, 0x05, 0x9c, 0x6e, 0xb2, 0x5c, 0xa1, 0x1c, 0x3b, 0x33, 0x67, 0x3e, 0x0a, 0xa7,
	0xfe, 0x01, 0xa1, 0x7f, 0x65, 0xb6, 0xba, 0xd1, 0x28, 0x66, 0xd1, 0xf4, 0xa7, 0x03, 0xde, 0x95,
	0x9d, 0x82, 0x9a, 0xe9, 0x35, 0x0c, 0xbe, 0x36, 0xb4, 0x96, 0x68, 0x72, 0x44, 0xd4, 0x0d, 0x65,
	0x06, 0x48, 0x5e, 0xc1, 0xd9, 0xba, 0x8a, 0xef, 0x51, 0xad, 0xbe, 0x65, 0x89, 0xba, 0x5b, 0xf1,
	0x72, 0x7c, 0x32, 0x73, 0xe6, 0x7d, 0xe6, 0x99, 0xf4, 0x97, 0x26, 0xfb, 0xa9, 0x24, 0xef, 0x60,
	0x18, 0x8b, 0x8a, 0x37, 0x4b, 0xf6, 0x35, 0xf7, 0xcb, 0x23, 0xee, 0x6b, 0x53, 0x6f, 0x37, 0xca,
	0x04, 0xff, 0xd8, 0x63, 0x6d, 0xd7, 0x7b, 0x0f, 0x46, 0x7b, 0x15, 0x9a, 0x82, 0xf7, 0x87, 0x28,
	0xf2, 0x02, 0xdc, 0x52, 0x54, 0x32, 0xc6, 0x55, 0x96, 0xe8, 0xf5, 0x5d, 0xf6, 0xd8, 0x24, 0x96,
	0x09, 0x79, 0x0b, 0xa0, 0xb2, 0x2d, 0xae, 0x64, 0xc4, 0x53, 0xd4, 0x0b, 0x3e, 0x24, 0xee, 0x73,
	0xb6, 0x45, 0xd6, 0x20, 0x98, 0xab, 0xda, 0x90, 0x9e, 0x83, 0xdb, 0xe5, 0xc9, 0x73, 0x18, 0x94,
	0x2a, 0x92, 0x4a, 0x0f, 0xe8, 0x33, 0xf3, 0x20, 0x4f, 0xa1, 0x8f, 0x3c, 0xb1, 0xba, 0x9b, 0x90,
	0x7e, 0x00, 0x4f, 0x5f, 0x8a, 0x61, 0x59, 0x08, 0x5e, 0x22, 0xb9, 0x00, 0xb7, 0x75, 0xb0, 0x1c,
	0x3b, 0xb3, 0xfe, 0x7c, 0x14, 0x8e, 0xfd, 0x3d, 0x8b, 0xfd, 0x5d, 0xe8, 0x2f, 0x2c, 0x80, 0xfd,
	0x86, 0xd2, 0xef, 0x0e, 0x3c, 0xeb, 0x2c, 0xea, 0xd8, 0x96, 0x30, 0x94, 0x58, 0x56, 0xb9, 0x6a,
	0xb9, 0x82, 0x63, 0xc7, 0x0f, 0x9b, 0x7c, 0x66, 0x3a, 0x16, 0x5c, 0xc9, 0x9a, 0xb5, 0xfd, 0x93,
	0x4b, 0x78, 0xb2, 0x5f, 0x68, 0xb4, 0xdc, 0x63, 0x6d, 0xf5, 0x35, 0x61, 0xa3, 0x79, 0x17, 0xe5,
	0x95, 0x39, 0x9b, 0xc3, 0xcc, 0xe3, 0xf2, 0xe4, 0x8d, 0x43, 0xe7, 0x40, 0x8e, 0x3d, 0x23, 0x04,
	0x1e, 0xf1, 0x68, 0x8b, 0xd6, 0x03, 0x1d, 0x87, 0x3f, 0x1c, 0x18, 0x5a, 0xbb, 0xc8, 0x02, 0x06,
	0xfa, 0x36, 0xe4, 0x1f, 0x5f, 0xd7, 0x64, 0xfa, 0x70, 0xad, 0x15, 0x43, 0x7b, 0xe4, 0x16, 0xdc,
	0x4e, 0x23, 0x99, 0xfe, 0x5d, 0xbf, 0xa6, 0xa3, 0xff, 0xbf, 0x0f, 0xed, 0xad, 0x4f, 0xf5, 0xbf,
	0x75, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x50, 0x25, 0x95, 0xf3, 0xc5, 0x03, 0x00, 0x00,
}
