// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package server_test

type mockLister struct {
	RoutesCalled chan bool
	RoutesOutput struct {
		Routes chan map[string]string
		Err    chan error
	}
}

func newMockLister() *mockLister {
	m := &mockLister{}
	m.RoutesCalled = make(chan bool, 100)
	m.RoutesOutput.Routes = make(chan map[string]string, 100)
	m.RoutesOutput.Err = make(chan error, 100)
	return m
}
func (m *mockLister) Routes() (routes map[string]string, err error) {
	m.RoutesCalled <- true
	return <-m.RoutesOutput.Routes, <-m.RoutesOutput.Err
}
