// Code generated by protoc-gen-go.
// source: analyst.proto
// DO NOT EDIT!

/*
Package intra is a generated protocol buffer package.

It is generated from these files:
	analyst.proto
	data_node.proto

It has these top-level messages:
	ExecuteInfo
	ExecuteResponse
	ReadMetricsInfo
	ReadMetricsResponse
*/
package intra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExecuteInfo struct {
	File string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Alg  string `protobuf:"bytes,2,opt,name=alg" json:"alg,omitempty"`
	Meta []byte `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *ExecuteInfo) Reset()                    { *m = ExecuteInfo{} }
func (m *ExecuteInfo) String() string            { return proto.CompactTextString(m) }
func (*ExecuteInfo) ProtoMessage()               {}
func (*ExecuteInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExecuteInfo) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ExecuteInfo) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *ExecuteInfo) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ExecuteResponse struct {
	Result map[string][]byte `protobuf:"bytes,1,rep,name=result" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExecuteResponse) GetResult() map[string][]byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecuteInfo)(nil), "intra.ExecuteInfo")
	proto.RegisterType((*ExecuteResponse)(nil), "intra.ExecuteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Analyst service

type AnalystClient interface {
	Execute(ctx context.Context, in *ExecuteInfo, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type analystClient struct {
	cc *grpc.ClientConn
}

func NewAnalystClient(cc *grpc.ClientConn) AnalystClient {
	return &analystClient{cc}
}

func (c *analystClient) Execute(ctx context.Context, in *ExecuteInfo, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := grpc.Invoke(ctx, "/intra.Analyst/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analyst service

type AnalystServer interface {
	Execute(context.Context, *ExecuteInfo) (*ExecuteResponse, error)
}

func RegisterAnalystServer(s *grpc.Server, srv AnalystServer) {
	s.RegisterService(&_Analyst_serviceDesc, srv)
}

func _Analyst_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalystServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intra.Analyst/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalystServer).Execute(ctx, req.(*ExecuteInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyst_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intra.Analyst",
	HandlerType: (*AnalystServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Analyst_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyst.proto",
}

func init() { proto.RegisterFile("analyst.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcc, 0x4b, 0xcc,
	0xa9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcc, 0x2b, 0x29, 0x4a,
	0x54, 0x72, 0xe7, 0xe2, 0x76, 0xad, 0x48, 0x4d, 0x2e, 0x2d, 0x49, 0xf5, 0xcc, 0x4b, 0xcb, 0x17,
	0x12, 0xe2, 0x62, 0x49, 0xcb, 0xcc, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x85, 0x04, 0xb8, 0x98, 0x13, 0x73, 0xd2, 0x25, 0x98, 0xc0, 0x42, 0x20, 0x26, 0x48, 0x55, 0x6e,
	0x6a, 0x49, 0xa2, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0xad, 0xd4, 0xc1, 0xc8, 0xc5,
	0x0f, 0x35, 0x29, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x8a, 0x8b, 0xad, 0x28,
	0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x49, 0x0f, 0x6c, 0xa9,
	0x1e, 0x9a, 0x3a, 0xbd, 0x20, 0xb0, 0x22, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0xa8, 0x0e, 0x29,
	0x4b, 0x2e, 0x6e, 0x24, 0x61, 0x90, 0x23, 0xb2, 0x53, 0x2b, 0xa1, 0xee, 0x02, 0x31, 0x85, 0x44,
	0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0xc1, 0x0e, 0xe3, 0x09, 0x82, 0x70, 0xac, 0x98, 0x2c,
	0x18, 0x8d, 0x9c, 0xb8, 0xd8, 0x1d, 0x21, 0x7e, 0x15, 0x32, 0xe7, 0x62, 0x87, 0x5a, 0x26, 0x24,
	0x84, 0x6a, 0x39, 0xc8, 0xbb, 0x52, 0x62, 0xd8, 0x1d, 0xa4, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x25,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x91, 0xc9, 0x72, 0x36, 0x01, 0x00, 0x00,
}
