// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package intra_test

import "github.com/apoydence/petasos/router"

type mockMetricsReader struct {
	MetricsCalled chan bool
	MetricsInput  struct {
		File chan string
	}
	MetricsOutput struct {
		Metric chan router.Metric
	}
}

func newMockMetricsReader() *mockMetricsReader {
	m := &mockMetricsReader{}
	m.MetricsCalled = make(chan bool, 100)
	m.MetricsInput.File = make(chan string, 100)
	m.MetricsOutput.Metric = make(chan router.Metric, 100)
	return m
}
func (m *mockMetricsReader) Metrics(file string) (metric router.Metric) {
	m.MetricsCalled <- true
	m.MetricsInput.File <- file
	return <-m.MetricsOutput.Metric
}
